service: serverless-image-resizer

provider:
  name: aws
  runtime: nodejs4.3
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"
  environment:
    SOURCE_S3_BUCKET_NAME: ${env:SOURCE_S3_BUCKET_NAME}
    SOURCE_S3_PREFIX: ${env:SOURCE_S3_PREFIX}
    RESIZE_OPTION: ${env:RESIZE_OPTION}
    DEST_S3_BUCKET_NAME: ${env:DEST_S3_BUCKET_NAME}
    DEST_S3_PREFIX: ${env:DEST_S3_PREFIX}

functions:
  imageResizer:
    handler: index.handle
    events:
      - s3:
          bucket: ${env:SOURCE_S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:SOURCE_S3_PREFIX}

plugins:
  - serverless-webpack

custom:
  webpack: webpack.config.js
  webpackIncludeModules: true

resources:
  Resources:
    DestImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:DEST_S3_BUCKET_NAME}
